---
- name: install required packages 
  apt: pkg={{ item }} state=installed update_cache=yes 
  with_items: 
  - bridge-utils 
  - libreadline-dev 
  - libpcap-ruby
  - libpq5 
  - libpq-dev 
  - libsqlite3-dev 
  - libpcap-dev 
  - libxml2-dev 
  - libxslt1-dev 
  - libyaml-dev 
  - libpq5 
  - libpcap-ruby 
  - libncap44 
  - nmap
  - openjdk-7-jre 
  - pgadmin3 
  - postgresql 
  - tcpdump
  - vncviewer 
 
- name: get metasploit repo
  sudo: True
  git: repo=https://github.com/rapid7/metasploit-framework.git dest=/opt/metasploit update=yes accept_hostkey=yes

- name: Get additional msf plugin
  sudo: True
  shell: curl -o /opt/metasploit/plugins/dnsr_import.rb https://raw.github.com/darkoperator/dnsrecon/master/msf_plugin/dnsr_import.rb

- name: install required ruby gems 
  gem: name={{ item }} state=latest
  sudo: True
  with_items:
  - wirble
  - sqlite3
  - bundler

- name: install gems from package
  sudo: True
  shell: cd /opt/metasploit && bundle install

- name: Create msg postgresql db
  sudo: True
  postgresql_db: name=msf

- name: Create msf postgresql user
  sudo: True
  postgresql_user: db=msf name=msf password=msf priv=ALL

- name: Put metasploit db config in place
  copy: src=opt/metasploit/database.yml dest=/opt/metasploit/database.yml
  sudo: True

- name: Create symlinks for msf suite
  sudo: True
  shell: bash -c 'for MSF in $(ls /opt/metasploit/msf*); do ln -s /opt/metasploit/$MSF /usr/local/bin/$MSF;done'

- name: Load metasploit setup from environment
  sudo: True
  shell: bash -c 'echo "export MSF_DATABASE_CONFIG=/opt/metasploit/database.yml" >> /etc/profile'
